#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Generate C haptics waveform arrays from 16-bit mono WAV files."""

import argparse
from pathlib import Path
import wave


def c_ident_suffix(symbol: str) -> str:
    suffix = symbol.upper()
    if suffix.startswith("HAPTICS_WAVEFORM_"):
        suffix = suffix[len("HAPTICS_WAVEFORM_") :]
    return suffix


def signed16_samples(path: Path, data: bytes) -> list[int]:
    out: list[int] = []

    for offset in range(0, len(data), 2):
        sample = int.from_bytes(data[offset : offset + 2], "little", signed=True)
        out.append(sample)

    return out


def read_wave(path: Path) -> tuple[int, list[int]]:
    with wave.open(str(path), "rb") as wav:
        channels = wav.getnchannels()
        sample_width = wav.getsampwidth()
        compression = wav.getcomptype()
        sample_rate = wav.getframerate()
        frames = wav.getnframes()
        data = wav.readframes(frames)

    if channels != 1 or sample_width != 2 or compression != "NONE":
        raise ValueError(f"{path}: expected uncompressed 16-bit mono PCM WAV")
    if len(data) != frames * sample_width:
        raise ValueError(f"{path}: frame count/data length mismatch")
    return sample_rate, signed16_samples(path, data)


def quantized_int8(data: list[int]) -> list[int] | None:
    out: list[int] = []

    for sample in data:
        if sample % 256 != 0:
            return None
        value = sample // 256
        if value < -128 or value > 127:
            return None
        out.append(value)
    return out


def emit_array(symbol: str, sample_rate: int, data: list[int]) -> list[str]:
    suffix = c_ident_suffix(symbol)
    int8_data = quantized_int8(data)
    if int8_data is not None:
        c_type = "int8_t"
        sample_format = "HAPTICS_WAVEFORM_SAMPLE_FORMAT_S8"
        values = int8_data
    else:
        c_type = "int16_t"
        sample_format = "HAPTICS_WAVEFORM_SAMPLE_FORMAT_S16"
        values = data

    lines = [
        f"#define HAPTICS_WAVEFORM_{suffix}_SAMPLE_RATE_HZ {sample_rate}U",
        f"#define HAPTICS_WAVEFORM_{suffix}_SAMPLES {len(values)}U",
        f"#define HAPTICS_WAVEFORM_{suffix}_SAMPLE_FORMAT {sample_format}",
        f"static const {c_type} {symbol}[] = {{",
    ]

    for offset in range(0, len(values), 12):
        chunk = values[offset : offset + 12]
        lines.append("\t" + ", ".join(str(value) for value in chunk) + ",")

    lines.append("};")
    return lines


def parse_input(value: str) -> tuple[str, Path]:
    if "=" not in value:
        raise argparse.ArgumentTypeError("expected SYMBOL=PATH")
    symbol, path = value.split("=", 1)
    if not symbol.isidentifier():
        raise argparse.ArgumentTypeError(f"{symbol!r} is not a valid C identifier")
    return symbol, Path(path)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--input", type=parse_input, action="append", required=True)
    args = parser.parse_args()

    output = [
        "/* Generated by scripts/haptics-wav-to-header.py; do not edit. */",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "#define HAPTICS_WAVEFORM_SAMPLE_FORMAT_S8 1",
        "#define HAPTICS_WAVEFORM_SAMPLE_FORMAT_S16 2",
        "",
    ]

    for index, (symbol, path) in enumerate(args.input):
        sample_rate, data = read_wave(path)
        if index:
            output.append("")
        output.extend(emit_array(symbol, sample_rate, data))

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(output) + "\n", encoding="ascii")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
